services:
  log-processor:
    build: .
    container_name: log_epro_processor
    restart: unless-stopped
    privileged: true
    
    # Variáveis de ambiente para configuração
    environment:
      - PYTHONUNBUFFERED=1
      - TZ=America/Sao_Paulo
      # Configurações do banco de dados (podem ser sobrescritas por .env)
      - DB_SERVER=${DB_SERVER:-192.168.2.15}
      - DB_DATABASE=${DB_DATABASE:-SISCNTRHC}
      - DB_USERNAME=${DB_USERNAME:-SISCNTRHC}
      - DB_PASSWORD=${DB_PASSWORD:-CtEp@2023}
      # Configurações do FTP (substitui SMB)
      - FTP_HOST=${FTP_HOST:-192.168.2.16}
      - FTP_PORT=${FTP_PORT:-23}
      - FTP_USERNAME=${FTP_USERNAME:-contrail}
      - FTP_PASSWORD=${FTP_PASSWORD:-contrail}
      - FTP_REMOTE_DIR=${FTP_REMOTE_DIR:-/}
    
    # Volumes para persistência de dados
    volumes:
      # Diretórios locais para processamento
      - ./logs:/app/logs
      - ./processed_csvs:/app/processed_csvs
      - ./reports:/app/reports
      - ./temp_unzipped_logs:/app/temp_unzipped_logs
      - ./processed_files.db:/app/processed_files.db
    
    # Rede para acesso ao banco externo
    networks:
      - LocalNetwork
    
    # Comando de inicialização (FTP - não precisa de montagem)
    command: >
      sh -c "\
        echo 'Iniciando processador de logs via FTP...' && \
        while true; do \
          echo 'Iniciando processador de logs...' && \
          python cli/main.py && \
          echo 'Processamento concluído. Aguardando próximo ciclo...' && \
          sleep 60; \
        done
      "
    
    # Configurações de recursos
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M
    
    # Configurações de logging
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  LocalNetwork:
    external: true
    ipam:
      config:
        - subnet: 172.30.0.0/16