services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jenkins
    restart: unless-stopped
    user: "0:0"               # Quick start: root (ver NOTA de segurança)
    ports:
      - "8081:8080"           # Jenkins UI (será por trás do Nginx/HTTPS)
      - "50000:50000"         # (opcional) agentes inbound
    environment:
      JENKINS_OPTS: "--prefix=/"             # evita problemas com path
      JAVA_OPTS: "-Djenkins.install.runSetupWizard=false -Xmx2048m"
      TZ: "America/Sao_Paulo"
      # Variáveis para automatização de deploys
      PROJECTS_ROOT: "/home/bigdata"
      # Projetos específicos
      GLPI_PATH: "/home/bigdata/glpi"
      METABASE_PATH: "/home/bigdata/metabase"
      N8N_PATH: "/home/bigdata/n8n"
      PORTAINER_PATH: "/home/bigdata/portainer"
      PROTHEUS_PATH: "/home/bigdata/PROTHEUS"
      SIM_PATH: "/home/bigdata/SIM"
      SISTEMAS_INTERNOS_PATH: "/home/bigdata/SISTEMAS_INTERNOS"
      SISTIJU_PATH: "/home/bigdata/SISTIJU"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock  # Jenkins controla Docker do host
      # Acesso aos projetos do servidor para automatização de deploys
      - /home/bigdata:/home/bigdata:rw  # Acesso somente leitura aos projetos
      - /home/bigdata/Jenkins:/home/bigdata/Jenkins:rw  # Acesso total ao diretório Jenkins
      # Projetos específicos para automatização
      - /home/bigdata/glpi:/home/bigdata/glpi:rw  # GLPI - Sistema de gestão
      - /home/bigdata/metabase:/home/bigdata/metabase:rw  # Metabase - BI/Analytics
      - /home/bigdata/n8n:/home/bigdata/n8n:rw  # N8N - Automação de workflows
      - /home/bigdata/portainer:/home/bigdata/portainer:rw  # Portainer - Gestão Docker
      - /home/bigdata/PROTHEUS:/home/bigdata/PROTHEUS:rw  # Protheus - ERP
      - /home/bigdata/SIM:/home/bigdata/SIM:rw  # SIM - Sistema de informações
      - /home/bigdata/SISTEMAS_INTERNOS:/home/bigdata/SISTEMAS_INTERNOS:rw  # Sistemas internos
      - /home/bigdata/SISTIJU:/home/bigdata/SISTIJU:rw  # SISTIJU - Sistema jurídico
    networks:
      - app_network

volumes:
  jenkins_home:

networks:
  app_network:
    external: true